/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/layout/AppTopbar.vue')['default']
    ConfirmacionModal: typeof import('./components/pagos/ConfirmacionModal.vue')['default']
    DetailSidePanel: typeof import('./components/historial-v2/DetailSidePanel.vue')['default']
    FilterDrawer: typeof import('./components/historial-v2/FilterDrawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RadioCard: typeof import('./components/pagos/RadioCard.vue')['default']
    ResultsCards: typeof import('./components/historial-v2/ResultsCards.vue')['default']
    ResultsTable: typeof import('./components/historial-v2/ResultsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1FormaDepago: typeof import('./components/pagos/Step1FormaDepago.vue')['default']
    Step2Registrar: typeof import('./components/pagos/Step2Registrar.vue')['default']
    Step3Confirmar: typeof import('./components/pagos/Step3Confirmar.vue')['default']
    StepperBar: typeof import('./components/pagos/StepperBar.vue')['default']
    ToastContainer: typeof import('./components/ui/ToastContainer.vue')['default']
  }
}
